spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate

postgres:
  datasource:
    jdbc-url: jdbc:postgresql://kesavan.db.elephantsql.com:5432/ijhrxdvd
    username: ijhrxdvd
    password: bXdwiCrTh4jcwlRrRSBt5qaLxHi8rwAn
    driverClassName: org.postgresql.Driver

mysql:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/pagamentos
    username: root
    password: Jj347189#
    driverClassName: com.mysql.cj.jdbc.Driver

spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha

parameter:
  example:
    sequence: M, 00, B, J, A
    list:
      M
      00
      B
      J
      A

server:
  servlet:
    context-path: /ecommerce
  error:
    include-stacktrace: never