spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate
        hbm2ddl:
          import_files:

postgres:
  datasource:
    jdbc-url: jdbc:postgresql://kesavan.db.elephantsql.com:5432/ijhrxdvd
    username: ijhrxdvd
    password:
    driverClassName: org.postgresql.Driver

mysql:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/pagamentos
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver